### ISSUE TITLE
'/api/get_pp_graph' - get performance point graph for profile page

### ISSUE THREAD

**Issue by yo-ru** [Yo-ru/gulag-web#30]

**Comment by varkaria** [comment]
ah i have no idea about this so
cmyui help : (

**Comment by cmyui** [comment]
Should the /api handlers be moved to gulag?

Also for storing pp/rank data about the user daily to create the charts, should this be done from gulag, or an external program? It will have to run at least once a day, and I guess ideally it should run even when the server isn't running.. perhaps this is a good job for an external cron, then the /api/get_pp_graph (and other /api handlers) can be in gulag.

**Comment by varkaria** [comment]
yeah it's should

**Comment by cmyui** [comment]
Alright, I've got some schoolwork to get done this week, once that's done I'll work on moving the api handlers & implementing more.

**Comment by varkaria** [comment]
but if it move to gulag
gulag should have some custom domain for api
and avatar what should we do?

**Comment by cmyui** [comment]
Yea, I can let users add their own domain for the /api routes (`like cmyui.codes/api/*`) in nginx, no issues there, with how I designed cmyui_pkg it allows for multiple domains.

For avatars, we could probably do the same sort of idea, like `a.cmyui.codes/*`.
