### ISSUE TITLE
got bad request when register new account

### ISSUE THREAD

**Issue by ProxyCC** [Yo-ru/gulag-web#42]
![image](https://user-images.githubusercontent.com/72607342/108232678-50f65300-7143-11eb-93b5-eba559762658.png)

**Comment by varkaria** [comment]
@Yo-ru

**Comment by yo-ru** [comment]
@morrisvdbeek would you please provide an error log? When this bad request happens?

```
nano config.py

# debug
debug = True
```

Then attempt to register again and please take a screenshot/copy-paste the output here and I will give you a diagnosis!

Thank you for contributing!

**Comment by ProxyCC** [comment]
> @morrisvdbeek would you please provide an error log? When this bad request happens?
> 
> ```
> nano config.py
> 
> # debug
> debug = True
> ```
> 
> Then attempt to register again and please take a screenshot/copy-paste the output here and I will give you a diagnosis!
> 
> Thank you for contributing!

yo I'm p dumb with this stuff so idk what I need to make a screenshot off but can you parsec me>???? my discord is TheNewWorld#6675

**Comment by yo-ru** [comment]
Fixed in commit 73ac0d8ba54173c74f2150e62784ccf9ce24aad7!

Thank you for the bug report and please continue to contribute to gulag-web!
