### ISSUE TITLE
X/XH instead of SS in user profile

### ISSUE THREAD

**Issue by Airkek** [Yo-ru/gulag-web#48]
![image](https://user-images.githubusercontent.com/45855057/108843806-411bba80-75ec-11eb-9d05-248952442557.png)
![image](https://user-images.githubusercontent.com/45855057/108854751-42071900-75f9-11eb-97ef-477da7e9b489.png)

also https://github.com/Yo-ru/gulag-web/blob/main/templates/profile.html
![image](https://user-images.githubusercontent.com/45855057/108844014-8f30be00-75ec-11eb-9c7d-95b7ac2a7728.png)

**Comment by yo-ru** [comment]
If you'd like make a pull request with the changes.
