### ISSUE TITLE
add setup instructions for other operating systems

### ISSUE THREAD

**Issue by yo-ru** [Yo-ru/gulag-web#6]

**Comment by yo-ru** [comment]
This will be postponed until further notice due to the lack of compatibility with @cmyui's library and windows.

**Comment by cmyui** [comment]
Ah yea this could take a while, simply put we just have many other priorities to get working before we go for pure usability stuff.
Windows support will likely come once the server is usable in production environments. ;)

**Comment by memsdm05** [comment]
Docker container?
