### ISSUE TITLE
Move /leaderboard to /lb

### ISSUE THREAD

**Issue by Atakku** [Yo-ru/gulag-web#72]
Renaming /leaderboard to /lb would make the url look a lot more neat and clean

**Comment by varkaria** [comment]
hmm i think it's good for me
but i can't decide it rn because we should wait for yo-ru decide it : )

**Comment by Atakku** [comment]
Made a PR #75

**Comment by varkaria** [comment]
@Yo-ru how about it?

**Comment by varkaria** [comment]
ok i think Yo-ru is busy so i decide it.
i think it's look good so i will merge and close it.
Thank you for contributing!
