### ISSUE TITLE
Avatar upload doesn't work; just deletes existing avatar

### ISSUE THREAD

**Issue by ghost** [Yo-ru/gulag-web#85]
![](https://1bl4.qonq.gq)
But only thing that happens is user's existing avatar is deleted if it exists.

**Comment by ghost** [comment]
https://github.com/Yo-ru/gulag-web/blob/b7fff4c70a6beb118f6fe182d29c27429db77886/blueprints/frontend.py#L147-L154

🤷 

Oh and yea nothing interesting in the log..
![](https://ux8d.qonq.gq)

**Comment by ghost** [comment]
o looks like it was fixed in that other fork? ![](https://7phq.qonq.gq)

**Comment by varkaria** [comment]
yep i fixed it in my fork
and now i think yo-ru seem quit this project
that's why i fork and continue in my fork

**Comment by yo-ru** [comment]
Closed as it was resolved in Varkaria's fork.
